# The keys are lowercase card names for consistent and case-insensitive lookups.
# Each card has a unique ID and an elixir cost.
CARDS_DATA = {
    "unknown": {"id": 0, "elixir": 0},
    "skeletons": {"id": 1, "elixir": 1},
    "electro spirit": {"id": 2, "elixir": 1},
    "ice spirit": {"id": 3, "elixir": 1},
    "fire spirit": {"id": 4, "elixir": 1},
    "goblins": {"id": 5, "elixir": 2},
    "spear goblins": {"id": 6, "elixir": 2},
    "wall breakers": {"id": 7, "elixir": 2},
    "the log": {"id": 8, "elixir": 2},
    "barbarian barrel": {"id": 9, "elixir": 2},
    "archers": {"id": 10, "elixir": 3},
    "knight": {"id": 11, "elixir": 3},
    "miner": {"id": 12, "elixir": 3},
    "princess": {"id": 13, "elixir": 3},
    "bandit": {"id": 14, "elixir": 3},
    "royal ghost": {"id": 15, "elixir": 3},
    "fisherman": {"id": 16, "elixir": 3},
    "ice wizard": {"id": 17, "elixir": 3},
    "electro wizard": {"id": 18, "elixir": 3},
    "mega minion": {"id": 19, "elixir": 3},
    "dart goblin": {"id": 20, "elixir": 3},
    "guards": {"id": 21, "elixir": 3},
    "elixir golem": {"id": 22, "elixir": 3},
    "valkyrie": {"id": 23, "elixir": 4},
    "hog rider": {"id": 24, "elixir": 4},
    "mini p.e.k.k.a.": {"id": 25, "elixir": 4},
    "lumberjack": {"id": 26, "elixir": 4},
    "night witch": {"id": 27, "elixir": 4},
    "magic archer": {"id": 28, "elixir": 4},
    "inferno dragon": {"id": 29, "elixir": 4},
    "ram rider": {"id": 30, "elixir": 4},
    "mother witch": {"id": 31, "elixir": 4},
    "battle ram": {"id": 32, "elixir": 4},
    "dark prince": {"id": 33, "elixir": 4},
    "baby dragon": {"id": 34, "elixir": 4},
    "hunter": {"id": 35, "elixir": 4},
    "executioner": {"id": 36, "elixir": 4},
    "bowler": {"id": 37, "elixir": 4},
    "cannon cart": {"id": 38, "elixir": 4},
    "wizard": {"id": 39, "elixir": 5},
    "giant": {"id": 40, "elixir": 5},
    "prince": {"id": 41, "elixir": 5},
    "witch": {"id": 42, "elixir": 5},
    "balloon": {"id": 43, "elixir": 5},
    "goblin giant": {"id": 44, "elixir": 5},
    "royal hogs": {"id": 45, "elixir": 5},
    "elite barbarians": {"id": 46, "elixir": 5},
    "sparky": {"id": 47, "elixir": 5},
    "phoenix": {"id": 48, "elixir": 5},
    "archer queen": {"id": 49, "elixir": 5},
    "golden knight": {"id": 50, "elixir": 5},
    "skeleton king": {"id": 51, "elixir": 5},
    "royal recruits": {"id": 52, "elixir": 6},
    "elixir collector": {"id": 53, "elixir": 6},
    "goblin drill": {"id": 54, "elixir": 6},
    "rocket": {"id": 55, "elixir": 6},
    "x-bow": {"id": 56, "elixir": 6},
    "mortar": {"id": 57, "elixir": 6},
    "the little prince": {"id": 58, "elixir": 6},
    "barbarians": {"id": 59, "elixir": 7},
    "minion horde": {"id": 60, "elixir": 7},
    "royal giant": {"id": 61, "elixir": 7},
    "giant skeleton": {"id": 62, "elixir": 7},
    "p.e.k.k.a.": {"id": 63, "elixir": 7},
    "mega knight": {"id": 64, "elixir": 7},
    "three musketeers": {"id": 65, "elixir": 9},
    "golem": {"id": 66, "elixir": 8},
    "cannon": {"id": 67, "elixir": 3},
    "tombstone": {"id": 68, "elixir": 3},
    "furnace": {"id": 69, "elixir": 4},
    "goblin cage": {"id": 70, "elixir": 4},
    "bomb tower": {"id": 71, "elixir": 5},
    "inferno tower": {"id": 72, "elixir": 5},
    "goblin hut": {"id": 73, "elixir": 5},
    "barbarian hut": {"id": 74, "elixir": 5},
    "rage": {"id": 75, "elixir": 1},
    "zap": {"id": 76, "elixir": 2},
    "giant snowball": {"id": 77, "elixir": 2},
    "arrows": {"id": 78, "elixir": 3},
    "tornado": {"id": 79, "elixir": 3},
    "fireball": {"id": 80, "elixir": 4},
    "poison": {"id": 81, "elixir": 4},
    "freeze": {"id": 82, "elixir": 4},
    "graveyard": {"id": 83, "elixir": 5},
    "lightning": {"id": 84, "elixir": 6},
    "fireball": {"id": 85, "elixir": 4},
    "zap": {"id": 86, "elixir": 2},
    "arrows": {"id": 87, "elixir": 3},
    "tornado": {"id": 88, "elixir": 3},
    "rocket": {"id": 89, "elixir": 6},
    "lightning": {"id": 90, "elixir": 6},
    "freeze": {"id": 91, "elixir": 4},
    "minions": {"id": 92, "elixir": 3},
    "bomber": {"id": 93, "elixir": 2},
    "musketeer": {"id": 94, "elixir": 4},
    "p.e.k.k.a": {"id": 95, "elixir": 7},
    "lava hound": {"id": 96, "elixir": 7},
    "goblin gang": {"id": 97, "elixir": 3},
    "rascals": {"id": 98, "elixir": 5},
    "zappies": {"id": 99, "elixir": 4},
    "flying machine": {"id": 100, "elixir": 4},
    "tesla": {"id": 101, "elixir": 4},
    "heal spirit": {"id": 102, "elixir": 1},
    "bats": {"id": 103, "elixir": 2},
    "royal delivery": {"id": 104, "elixir": 3},
    "goblin barrel": {"id": 105, "elixir": 3},
    "skeleton barrel": {"id": 106, "elixir": 3},
    "clone": {"id": 107, "elixir": 3},
    "mirror": {"id": 108, "elixir": 10},
    "poison": {"id": 109, "elixir": 4},
    "earthquake": {"id": 110, "elixir": 3},
    "archers queen": {"id": 111, "elixir": 5},
    "mighty miner": {"id": 112, "elixir": 4},
    "little prince": {"id": 113, "elixir": 3}
}

# For convenience, create a mapping from ID back to the card name and data
ID_TO_CARD = {data["id"]: {"name": name, **data} for name, data in CARDS_DATA.items()}

# List of spell cards, also in lowercase
SPELL_CARDS = [
    "the log", "barbarian barrel", "rage", "zap", "giant snowball", "arrows",
    "tornado", "fireball", "poison", "freeze", "graveyard", "lightning", "rocket",
    "goblin barrel", "skeleton barrel", "clone", "mirror", "earthquake"
]